openapi: 3.0.0
info:
  description: |
    api ugly dev
  version: "1.0.0"
  title: Ugly api
servers:
  - url: "http://api.dev.ugly.gallery/api/v1"

tags:
  - name: post
    description: Посты
  - name: user
    description: Пользователи
  - name: category
    description: Категории
  - name: auth
    description: Авторизация
paths:
  /login:
    post:
      tags:
        - auth
      summary: Залогиниться
      description: Залогиниться
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInputParams'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Login"
  /logout:
    post:
      security:
        - Bearer: [ ]
      tags:
        - auth
      summary: Разлогиниться
      description: Разлогиниться
      operationId: logout
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Logout"
  /register:
    post:
      tags:
        - auth
      summary: Регистрация
      description: Регистрация
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInputParams'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Register"
  /post:
    get:
      tags:
        - post
      summary: Получить посты
      description: Получить посты
      operationId: getPosts
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PostGet"
  /author:
    get:
      tags:
        - user
      summary: Получить всех авторов постов
      description: Получить всех авторов постов
      operationId: getAuthors
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AuthorGet"
  /category:
    get:
      tags:
        - category
      summary: Получить все категории
      description: Получить все категории
      operationId: getCategories
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryGet"
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".
  schemas:
    Login:
      type: object
      properties:
        data:
          type: "object"
          properties:
            user:
              $ref: "#/components/schemas/User"
            token:
              type: string
    Logout:
      type: array
    Register:
      type: object
      properties:
        data:
          type: "object"
          properties:
            user:
              $ref: "#/components/schemas/User"
            token:
              type: string
    LoginInputParams:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
    RegisterInputParams:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        device_name:
          type: string
    PostGet:
      type: object
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Post"
        meta:
          type: object
    AuthorGet:
      type: object
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/User"
        meta:
          type: object
    CategoryGet:
      type: object
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Category"
        meta:
          type: object
    Post:
      type: 'object'
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        views_counter:
          type: integer
        is_published:
          type: boolean
          default: true
        photo:
          type: string
        user:
          type: object
          $ref: "#/components/schemas/User"
        categories:
          type: "array"
          items:
            $ref: "#/components/schemas/Category"
    User:
      type: 'object'
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        avatar:
          type: string
    Category:
      type: 'object'
      properties:
        id:
          type: integer
        name:
          type: string
        photo:
          type: string
